import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { barbers, brand, services } from "@/lib/barbershop-data";
import { cn } from "@/lib/utils";

export const Route=createFileRoute("/agendamento")({head:()=>({meta:[{title:"Agendar horário — Fino Trato Barbearia"},{name:"description",content:"Escolha serviço, profissional, dia e horário para solicitar sua reserva."},{property:"og:title",content:"Agendar horário — Fino Trato Barbearia"},{property:"og:description",content:"Reserve seu próximo atendimento em poucos passos."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:BookingPage});
const times=["09:00","10:30","12:00","14:00","15:30","17:00","18:30"];
function BookingPage(){
 const [step,setStep]=useState(1); const [service,setService]=useState(""); const [barber,setBarber]=useState(""); const [date,setDate]=useState(""); const [time,setTime]=useState(""); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [notes,setNotes]=useState(""); const [sent,setSent]=useState(false);
 const canContinue=useMemo(()=>step===1?Boolean(service&&barber):step===2?Boolean(date&&time):Boolean(name.trim()&&phone.trim()),[step,service,barber,date,time,name,phone]);
 const formattedDate=useMemo(()=>{const [year,month,day]=date.split("-");return year&&month&&day?`${day}/${month}/${year}`:date},[date]);
 const whatsappMessage=useMemo(()=>{const lines=[`Olá! Gostaria de agendar um horário na ${brand.name}.`,`Serviço: ${service}`,`Profissional: ${barber}`,`Data: ${formattedDate}`,`Horário: ${time}`,`Nome: ${name}`,`Celular: ${phone}`];if(notes.trim())lines.push(`Observações: ${notes.trim()}`);return lines.join("\n")},[service,barber,formattedDate,time,name,phone,notes]);
 const whatsappUrl=useMemo(()=>`${brand.whatsappHref}?text=${encodeURIComponent(whatsappMessage)}`,[whatsappMessage]);
 const submit=()=>{if(!canContinue)return;window.open(whatsappUrl,"_blank","noopener,noreferrer");setSent(true)};
 if(sent)return <section className="bg-grain min-h-[75vh] bg-surface-deep px-5 pb-20 pt-36 text-surface-deep-foreground"><div className="mx-auto max-w-xl text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-primary text-primary-foreground"><Check className="size-7"/></span><p className="eyebrow mt-7">Quase lá</p><h1 className="mt-3 font-display text-5xl font-semibold">Confirme pelo WhatsApp.</h1><p className="mt-5 leading-7 text-surface-deep-muted">Abrimos o WhatsApp com sua solicitação pronta. Envie a mensagem para a equipe confirmar seu horário.</p><div className="mt-8 rounded-2xl border border-surface-deep-border p-6 text-left text-sm"><p><strong>Serviço:</strong> {service}</p><p className="mt-2"><strong>Profissional:</strong> {barber}</p><p className="mt-2"><strong>Quando:</strong> {formattedDate} às {time}</p></div><div className="mt-8 flex flex-wrap justify-center gap-3"><Button asChild><a href={whatsappUrl} target="_blank" rel="noreferrer">Abrir WhatsApp novamente</a></Button><Button variant="outline" onClick={()=>{setSent(false);setStep(1)}}>Fazer outro agendamento</Button></div></div></section>;
 return <section className="bg-muted pb-20 pt-18"><div className="mx-auto max-w-5xl px-5 pt-14 sm:px-8"><p className="eyebrow">Agendamento online</p><h1 className="mt-3 font-display text-5xl font-semibold sm:text-6xl">Escolha seu momento.</h1><p className="mt-4 text-sm text-muted-foreground">Finalize direto pelo WhatsApp — sem cadastro, sem burocracia.</p><div className="mt-10 grid grid-cols-3 gap-2" aria-label="Etapas do agendamento">{["Serviço","Horário","Seus dados"].map((label,index)=><div key={label} className={cn("border-t-2 pt-3 text-xs font-bold uppercase tracking-widest",step>=index+1?"border-primary text-foreground":"border-border text-muted-foreground")}><span className="mr-2 text-primary">0{index+1}</span>{label}</div>)}</div><div className="mt-8 rounded-2xl bg-background p-5 shadow-sm sm:p-9">{step===1&&<StepOne service={service} setService={setService} barber={barber} setBarber={setBarber}/>} {step===2&&<StepTwo date={date} setDate={setDate} time={time} setTime={setTime}/>} {step===3&&<StepThree name={name} setName={setName} phone={phone} setPhone={setPhone} notes={notes} setNotes={setNotes}/>}<div className="mt-9 flex items-center justify-between border-t border-border pt-6"><Button variant="ghost" disabled={step===1} onClick={()=>setStep((s)=>Math.max(1,s-1))}><ChevronLeft/> Voltar</Button>{step<3?<Button disabled={!canContinue} onClick={()=>setStep((s)=>Math.min(3,s+1))}>Continuar <ChevronRight/></Button>:<Button disabled={!canContinue} onClick={submit}>Confirmar no WhatsApp <Check/></Button>}</div></div></div></section>;
}
function Choice({selected,onClick,children}:{selected:boolean;onClick:()=>void;children:ReactNode}){return <button type="button" onClick={onClick} className={cn("w-full rounded-xl border p-5 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",selected?"border-primary bg-muted":"border-border hover:border-primary")}>{children}</button>}
function StepOne({service,setService,barber,setBarber}:{service:string;setService:(v:string)=>void;barber:string;setBarber:(v:string)=>void}){return <div><h2 className="font-display text-3xl font-semibold">O que vamos fazer?</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{services.slice(0,4).map(s=><Choice key={s.name} selected={service===s.name} onClick={()=>setService(s.name)}><div className="flex justify-between gap-3"><strong>{s.name}</strong><span className="text-primary">{s.price}</span></div><span className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><Clock3 className="size-3"/>{s.duration}</span></Choice>)}</div><h2 className="mt-9 font-display text-3xl font-semibold">Com quem?</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{barbers.map(b=><Choice key={b.name} selected={barber===b.name} onClick={()=>setBarber(b.name)}><UserRound className="size-5 text-primary"/><strong className="mt-3 block">{b.name}</strong><span className="mt-1 block text-xs text-muted-foreground">{b.role.split(" · ")[1]}</span></Choice>)}</div></div>}
function StepTwo({date,setDate,time,setTime}:{date:string;setDate:(v:string)=>void;time:string;setTime:(v:string)=>void}){return <div><h2 className="font-display text-3xl font-semibold">Quando fica melhor?</h2><label className="mt-6 block text-xs font-bold uppercase tracking-[0.12em]" htmlFor="date">Data</label><div className="relative mt-2"><CalendarDays className="pointer-events-none absolute left-4 top-3.5 size-5 text-primary"/><input id="date" type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-12 w-full rounded-lg border border-input bg-background pl-12 pr-4 focus:outline-none focus:ring-2 focus:ring-ring"/></div><p className="mt-8 text-xs font-bold uppercase tracking-[0.12em]">Horários disponíveis</p><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{times.map(value=><Choice key={value} selected={time===value} onClick={()=>setTime(value)}><span className="flex items-center justify-center gap-2"><Clock3 className="size-4 text-primary"/>{value}</span></Choice>)}</div></div>}
function StepThree({name,setName,phone,setPhone,notes,setNotes}:{name:string;setName:(v:string)=>void;phone:string;setPhone:(v:string)=>void;notes:string;setNotes:(v:string)=>void}){return <div><h2 className="font-display text-3xl font-semibold">Como podemos falar com você?</h2><div className="mt-7 grid gap-6 sm:grid-cols-2"><label className="text-xs font-bold uppercase tracking-[0.12em]">Nome completo<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 h-12 w-full rounded-lg border border-input bg-background px-4 text-sm font-normal normal-case tracking-normal focus:outline-none focus:ring-2 focus:ring-ring" placeholder="Seu nome"/></label><label className="text-xs font-bold uppercase tracking-[0.12em]">Celular<input value={phone} onChange={e=>setPhone(e.target.value)} className="mt-2 h-12 w-full rounded-lg border border-input bg-background px-4 text-sm font-normal normal-case tracking-normal focus:outline-none focus:ring-2 focus:ring-ring" placeholder="(11) 99999-9999" inputMode="tel"/></label></div><label className="mt-6 block text-xs font-bold uppercase tracking-[0.12em]">Observações<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2 min-h-28 w-full resize-y rounded-lg border border-input bg-background p-4 text-sm font-normal normal-case tracking-normal focus:outline-none focus:ring-2 focus:ring-ring" placeholder="Algo que devemos saber?"/></label></div>}